### ISSUE TITLE
I have the same issue

### ISSUE THREAD

**Issue by esromneb** [rav2040/ts-jest-error-could-not-find-source-file#1]
I am getting the same error you are randomly in my setup.  What worked for me was:

`./node_modules/.bin/jest --clearCache`

As described here:

https://medium.com/@prins.p/could-not-find-source-file-6c36553f47f2

Hope that helps!

**Comment by rav2040** [comment]
This bug has already been fixed as discussed here: https://github.com/kulshekhar/ts-jest/issues/1506

Now just waiting for the next release.
